<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="George Acostalemus">
<meta name="dcterms.date" content="2025-12-15">

<title>Deforestation Dynamics on New Britain, Papua New Guinea (2001–2023)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="New Britain_files/libs/clipboard/clipboard.min.js"></script>
<script src="New Britain_files/libs/quarto-html/quarto.js"></script>
<script src="New Britain_files/libs/quarto-html/popper.min.js"></script>
<script src="New Britain_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="New Britain_files/libs/quarto-html/anchor.min.js"></script>
<link href="New Britain_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="New Britain_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="New Britain_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="New Britain_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="New Britain_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data Sources</a></li>
  <li><a href="#data-processing-methods" id="toc-data-processing-methods" class="nav-link" data-scroll-target="#data-processing-methods">Data Processing Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="New-Britain.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Deforestation Dynamics on New Britain, Papua New Guinea (2001–2023)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>George Acostalemus </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Load R packages</strong></p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>New Britain is the largest island in the Bismarck Archipelago of Papua New Guinea (PNG) and is divided administratively into two provinces: East New Britain and West New Britain. The island is characterized by extensive tropical forest cover, high biodiversity, and increasing pressure from agricultural expansion, particularly plantation agriculture. Deforestation is the large scale of clearing forest for other land use such as farming, or urban development. One of the key causes are usually wildfires, droughts, or storms while agricultural causes are harvesting for materials.</p>
<p>Deforestation in Papua New Guinea has important implications for biodiversity conservation, carbon storage, and local livelihoods. While national level trends are often reported, sub national patterns of forest loss can vary substantially. Understanding how deforestation has evolved differently across East and West New Britain provides insight into the spatial and temporal dynamics of environmental change on the island.</p>
<p>The purpose of this project is to examine patterns of forest loss on New Britain from 2001 to 2023, with a specific focus on comparing annual and cumulative deforestation trends between East and West New Britain. The analysis emphasizes visualization and interactive exploration to demonstrate the use of R, Quarto, and Shiny for environmental data analysis.</p>
</section>
<section id="data-sources" class="level2">
<h2 class="anchored" data-anchor-id="data-sources">Data Sources</h2>
<p>Multiple publicly available datasets were used in this analysis:</p>
<ul>
<li><p><strong>Global Forest Watch (GFW)</strong>: Subnational tree cover loss data (2001–2023), reported annually in hectares. Data were accessed at the provincial (ADM1) level for Papua New Guinea.</p></li>
<li><p><strong>Humanitarian Data Exchange (HDX)</strong>: Administrative boundary shapefiles for Papua New Guinea provinces, used to map East and West New Britain.</p></li>
<li><p><strong>Baseline Forest Extent</strong>: Forest area in the year 2000 (threshold = 0) from the GFW dataset, used as a reference for normalization.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-PNG-ADM1' from data source 
  `/Users/user/Documents/MA-615/Island Project/geoBoundaries-PNG-ADM1-all/geoBoundaries-PNG-ADM1.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 22 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 140.8405 ymin: -11.65616 xmax: 159.4818 ymax: -0.757591
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
</section>
<section id="data-processing-methods" class="level2">
<h2 class="anchored" data-anchor-id="data-processing-methods">Data Processing Methods</h2>
<p>Annual tree cover loss (in hectares) was extracted for East and West New Britain from the Global Forest Watch subnational dataset. Data were filtered to include only threshold = 0, corresponding to all tree cover regardless of canopy density.</p>
<p>To allow meaningful comparison between provinces of different sizes, forest loss was analyzed in both absolute terms (hectares) and normalized terms (percentage of baseline forest area). Annual percentage forest loss was calculated by dividing annual loss by baseline forest extent in 2000. Cumulative forest loss was computed as the running sum of annual losses over time.</p>
<p>Administrative boundaries from HDX were harmonized with the forest loss dataset by standardizing province names prior to spatial joins. Choropleth maps were generated using fixed color scales based on the full range of values across all years to ensure temporal comparability.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 46 × 3
   province          year loss_ha
   &lt;chr&gt;            &lt;int&gt;   &lt;dbl&gt;
 1 East New Britain  2001    1152
 2 East New Britain  2002    1623
 3 East New Britain  2003    2167
 4 East New Britain  2004    2834
 5 East New Britain  2005    2022
 6 East New Britain  2006    3225
 7 East New Britain  2007    3643
 8 East New Britain  2008    6322
 9 East New Britain  2009    2544
10 East New Britain  2010    8496
# ℹ 36 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="New-Britain_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This graph shows annual forest loss in East and West New Britain from 2001 to 2023. Over the full study period, West New Britain consistently experienced higher annual forest loss than East New Britain, indicating sustained and comparatively greater deforestation pressure.</p>
<p>Both provinces exhibit substantial year-to-year variability, with several pronounced spikes rather than a smooth trend. West New Britain shows a notable peak around 2015, where annual forest loss exceeds 30,000 hectares, followed by a decline and then renewed increases in the early 2020s. East New Britain also shows episodic increases, including a sharp spike in 2022, suggesting periods of intensified land conversion rather than gradual change.</p>
<p>Despite these fluctuations, the overall pattern indicates that deforestation pressure intensified after approximately 2010 in both provinces, with West New Britain remaining the dominant contributor to forest loss throughout the period.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  shapeName year loss_ha
1 East New Britain Province 2023    7263
2 West New Britain Province 2023   11896</code></pre>
</div>
</div>
<p>The output of this table quantifies forest loss in 2023 and confirms the visual patterns shown in the figures. West New Britain lost 11,896 hectares of forest in 2023, compared to 7,263 hectares in East New Britain. This represents a difference of more than 4,600 hectares in a single year, underscoring the magnitude of disparity between the two provinces.</p>
<p>Taken together, the table and figures demonstrate that West New Britain not only exhibits higher long-term cumulative forest loss, but also continues to experience higher annual losses in recent years, suggesting that deforestation pressures remain ongoing rather than historical.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="New-Britain_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This figure is a maps forest loss in New Britain for the year 2023. The spatial pattern reinforces the temporal trends observed in Figure 1. West New Britain exhibits substantially higher forest loss than East New Britain, as indicated by the darker shading across the western portion of the island.</p>
<p>This spatial contrast highlights a clear east–west divide in deforestation intensity. While both provinces experienced forest loss in 2023, loss in West New Britain was more extensive, suggesting stronger or more concentrated land-use pressures in that province during the most recent year of analysis.</p>
<p>Overall, both temporal and spatial analyses indicate persistent and uneven deforestation across New Britain, with West New Britain consistently experiencing greater forest loss than East New Britain, particularly during periods of intensified deforestation activity.</p>
<p><strong>Get Province Forest Area</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  province         forest_area_ha
  &lt;chr&gt;                     &lt;dbl&gt;
1 East New Britain        1535341
2 West New Britain        2038523</code></pre>
</div>
</div>
<p><strong>Cumulative Forest Loss</strong></p>
<div class="cell">
<div class="cell-output-display">
<p></p><div style="width: 100% ; height: 400px ; text-align: center; box-sizing: border-box; -moz-box-sizing: border-box; -webkit-box-sizing: border-box;" class="muted well">Shiny applications not supported in static R Markdown documents</div><p></p>
</div>
</div>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="annual-forest-loss" class="level3">
<h3 class="anchored" data-anchor-id="annual-forest-loss">Annual Forest Loss</h3>
<p>Annual forest loss varied substantially over time in both provinces. West New Britain consistently exhibited higher annual forest loss than East New Britain, with several years showing pronounced spikes. These patterns are visible in the animated map below, which shows annual forest loss in hectares from 2001 to 2023.</p>
<p><img src="images/annual_forest_loss_new_britain.gif" class="img-fluid"></p>
</section>
<section id="cumulative-forest-loss" class="level3">
<h3 class="anchored" data-anchor-id="cumulative-forest-loss">Cumulative Forest Loss</h3>
<p>When forest loss is aggregated cumulatively, differences between the two provinces become more pronounced. West New Britain experienced substantially greater cumulative forest loss over the study period, reflecting sustained deforestation pressure over time. Cumulative forest loss provides a clearer picture of long-term environmental change than annual values alone.</p>
<p><img src="images/forestloss.gif" class="img-fluid"></p>
</section>
<section id="normalized-forest-loss" class="level3">
<h3 class="anchored" data-anchor-id="normalized-forest-loss">Normalized Forest Loss</h3>
<p>To account for differences in province size, forest loss was also expressed as a percentage of baseline forest area. Normalized results confirm that West New Britain not only lost more forest in absolute terms, but also experienced higher rates of forest loss relative to its total forest area. This suggests structural differences in land use and development pressures between the two provinces.</p>
<p><img src="images/annual_pct_forest_loss.gif" class="img-fluid" width="686"></p>
<p><img src="images/cumulative_pct_forest_loss-01.gif" class="img-fluid"></p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>Results indicate substantial and persistent deforestation on New Britain between 2001 and 2023, with West New Britain experiencing consistently higher forest loss than East New Britain. These differences likely reflect variation in land-use practices, including the expansion of plantation agriculture and infrastructure development.</p>
<p>The use of both absolute and normalized metrics highlights the importance of considering scale when comparing regions. While annual forest loss fluctuates, cumulative and percentage-based measures reveal long-term trends that may be obscured in year-to-year analyses.</p>
<p>Several limitations should be noted. Forest loss estimates are derived from satellite data and may be subject to classification error. Additionally, this analysis does not distinguish among drivers of deforestation, which could be explored in future work.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This project demonstrates how R, Quarto, and Shiny can be used to analyze and communicate environmental change using spatial and temporal data. By focusing on New Britain, the analysis highlights meaningful sub national variation in deforestation patterns and illustrates the value of interactive visualization for exploring complex environmental data sets.</p>
<p>Future extensions could incorporate land cover transitions, population data, or economic indicators to further investigate the drivers and consequences of deforestation on the island.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Global Forest Watch. (2024). Tree cover loss data. <a href="https://www.globalforestwatch.org/" class="uri">https://www.globalforestwatch.org/</a><br>
Humanitarian Data Exchange (HDX). Papua New Guinea administrative boundaries. <a href="https://data.humdata.org/dataset/cod-ab-png" class="uri">https://data.humdata.org/dataset/cod-ab-png</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>